Onboarding python
uber/piranha pull request #248
Opened 2022-09-19 16:25 UTC by dvmarcilio

This PR adds the Python grammar as a dependency and a custom cleanup demo.

## Demo

The demo deletes a given string literal that is a list element. If this string literal is the only element, a custom cleanup will delete an assignment to the resulting empty list (e.g., `deps3` in the example below).

Given that the argument string literal is `dependency2`.

Before

```python
deps = ['dependency1', 'dependency2', 'dependency3']
nums = [1, 2, 3]
deps2 = ["dependency2", "dependency1"]
deps3 = ['dependency2']
empty_list = []
```

After

```python
deps = ['dependency1', 'dependency3']
nums = [1, 2, 3]
deps2 = ["dependency1"]
empty_list = []
```

2022-09-19 18:41 UTC, ketkarameya commented on polyglot/piranha/demo/find_replace_custom_cleanup_demos.py
> +    Deletes the @str_literal (substitution in `piranha_arguments`) string literal when present as list element.
```suggestion
    Deletes the string literal `@str_literal` (from `substitutions` in `piranha_arguments.toml`) if it appears as a list element.
```

2022-09-19 18:44 UTC, ketkarameya commented on polyglot/piranha/demo/find_replace_custom_cleanup/python/configurations/rules.toml
> +        (string) @s
nicer names? say `@string_literal`

2022-09-19 18:49 UTC, ketkarameya commented on polyglot/piranha/demo/find_replace_custom_cleanup_demos.py
> +def python_demo():
Can we please add another small rule that updates "dependency3" -> "dependency3_1"

2022-09-19 18:49 UTC, ketkarameya requested changes
Left a few comments.

2022-09-19 18:50 UTC, ketkarameya commented on polyglot/piranha/demo/find_replace_custom_cleanup/python/only_lists.py
> +deps = ['dependency1', 'dependency2', 'dependency3']
Add license to all new files.

2022-09-19 18:56 UTC, ketkarameya commented on polyglot/piranha/test-resources/python/structural_find/input/list_as_arg.py
> +func_call(
license

2022-09-19 18:56 UTC, ketkarameya commented on polyglot/piranha/test-resources/python/structural_find/input/only_lists.py
> +deps = ['dependency1', 'dependency2', 'dependency3']
license

2022-09-19 20:21 UTC, dvmarcilio commented
Thanks for the review and the suggestions. I tried to address all of them.
I updated `dependency1` -> `dependency1_1` so we replace both `'dependency1'` and `"dependency1"` (single and double quotes).

If the changes are good enough, feel free to squash the commits.

2022-09-20 01:39 UTC, ketkarameya approved these changes
LGTM.

2022-09-20 02:24 UTC, merged